### ISSUE TITLE
Setting flair does not work

### ISSUE THREAD

**Issue by lbenedetto** [euparkeria/RedditJerk#7]
I logged into the RedditApi instance with OAuth. Removing and approving posts works fine, so I know I am authenticated properly. But I am unable to assign linkFlair to any posts.
For example: 
reddit.linkFlair("dankmemes", "5ryer0", "Meta", "");

No error messages are returned, everything seems to go through fine. I ran through it in a debugger and found that your post url actually has reddit.com//r/subName (double slash before r) but that shouldn't affect anything.

**Comment by euparkeria** [comment]
Setting a link flair requires a fullname ID, like this: reddit.linkFlair("dankmemes", "t3_5ryer0", "Meta", "");

**Comment by Shamim1977** [comment]
This is how I call it:
Reddit red = RedditApi.getRedditInstance("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36");
         
         User myUser = red.login("xxxxxx", "xxxxxxxx", "tnMm0-IkXE3efg", "-dfMhtBBFxl1tdHlRGeITZ-O690");
         String tUserID = myUser.getId().toString(); 
         String tUserName = myUser.getName();
         
         if (!tUserName.equals("")){
             red.Submit("u/Shm55777", "People trying colonise planets and stars, I am not getting extra time after prayers.", "I am of no use", "self");
         }

It fetches  tUserID & tUserName  properly. But does not submit and gives this error-

Exception in thread "AWT-EventQueue-0" ga.dryco.redditjerk.exceptions.RedditJerkException: Rate Limit Error, try later
	at ga.dryco.redditjerk.datamodels.deserializers.PostReturnDeserializer.deserialize(PostReturnDeserializer.java:20)
	at ga.dryco.redditjerk.datamodels.deserializers.PostReturnDeserializer.deserialize(PostReturnDeserializer.java:13)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at ga.dryco.redditjerk.implementation.RedditApi.getDataObject(RedditApi.java:892)
	at ga.dryco.redditjerk.implementation.RedditApi.Submit(RedditApi.java:425)

...What am I doing wrong? ...I am not sure how to authenticate the request, thats why just placing a login call just before submit.

Please suggest.
Sam
